# See https://github.com/nextcloud/docker/?tab=readme-ov-file#running-this-image-with-docker-compose

services:
  db:
    # Note: Check the recommend version here: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
    image: mariadb:lts
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - db:/var/lib/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend

  # Note: Redis is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/redis
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
  
  # Nextcloud apache container config:
  nc-app:
    image: nextcloud:30.0.13-apache
    restart: always
    # Enable ports for testing at localhost:8080
    # ports:
    #  - 8080:80
    depends_on:
      - redis
      - db
    volumes:
      - nextcloud:/var/www/html
      - config:/var/www/html/config
      - data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      # See https://github.com/nextcloud/docker/?tab=readme-ov-file#using-the-image-behind-a-reverse-proxy-and-specifying-the-server-host-and-protocol
      # See also https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html
      - TRUSTED_PROXIES=172.16.0.2
      - APACHE_DISABLE_REWRITE_IP=1
    networks:
      backend:
      nc-proxy:
        # static ip to allow TRUSTED_PROXIES to be set above
        ipv4_address: 172.16.0.3

volumes:
  nextcloud:
  config:
  data:
  db:

networks:
  backend: 
  nc-proxy:
    external: true
